/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gitflow.test;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
	System.out.println("This git thing is starting to get complicated, but I'm getting the hang of it.");
    }
}
